#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lookup
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FluorideCareDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_User(tbl_User instance);
    partial void Updatetbl_User(tbl_User instance);
    partial void Deletetbl_User(tbl_User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::lookup.Properties.Settings.Default.FluorideCareDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_User> tbl_Users
		{
			get
			{
				return this.GetTable<tbl_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User")]
	public partial class tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_user;
		
		private string _nama;
		
		private string _jenis_kelamin;
		
		private System.DateTime _tanggal_lahir;
		
		private string _alamat;
		
		private string _kota;
		
		private int _kodepos;
		
		private string _telepon;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_userChanging(int value);
    partial void Onid_userChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    partial void Ontanggal_lahirChanging(System.DateTime value);
    partial void Ontanggal_lahirChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    partial void OnkodeposChanging(int value);
    partial void OnkodeposChanged();
    partial void OnteleponChanging(string value);
    partial void OnteleponChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tbl_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal_lahir", DbType="Date NOT NULL")]
		public System.DateTime tanggal_lahir
		{
			get
			{
				return this._tanggal_lahir;
			}
			set
			{
				if ((this._tanggal_lahir != value))
				{
					this.Ontanggal_lahirChanging(value);
					this.SendPropertyChanging();
					this._tanggal_lahir = value;
					this.SendPropertyChanged("tanggal_lahir");
					this.Ontanggal_lahirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kodepos", DbType="Int NOT NULL")]
		public int kodepos
		{
			get
			{
				return this._kodepos;
			}
			set
			{
				if ((this._kodepos != value))
				{
					this.OnkodeposChanging(value);
					this.SendPropertyChanging();
					this._kodepos = value;
					this.SendPropertyChanged("kodepos");
					this.OnkodeposChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telepon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telepon
		{
			get
			{
				return this._telepon;
			}
			set
			{
				if ((this._telepon != value))
				{
					this.OnteleponChanging(value);
					this.SendPropertyChanging();
					this._telepon = value;
					this.SendPropertyChanged("telepon");
					this.OnteleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
